"""Generate a synthetic liquidity cash-flow dataset (bank + corporate treasury) as star-schema CSVs.

Usage:
    python generate.py [--config CONFIG] [--out data/liquidity] [--seed 42] [--size small|medium]
                       [--entity bank|corporate|both] [--force]

The output folder gets a `.liqsim` marker; the generator refuses to write into a non-empty folder
without that marker (protects real data) unless --force is given.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from liqsim import bank as bank_mod  # noqa: E402
from liqsim import corporate as corp_mod  # noqa: E402
from liqsim import docs, metrics, scenarios  # noqa: E402
from liqsim.common import (DAY, Writer, buckets, fx_history, load_config, make_calendar, nm_bucket_key,  # noqa: E402
                           projection_scenarios, reporting_currency)

DEFAULT_CONFIG = Path(__file__).resolve().parent.parent / "config" / "default.yaml"
MARKER = ".liqsim"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default=str(DEFAULT_CONFIG))
    ap.add_argument("--out", default="data/liquidity")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--size", default=None, help="size preset from the config (small | medium)")
    ap.add_argument("--entity", choices=["bank", "corporate", "both"], default="both")
    ap.add_argument("--force", action="store_true", help="write even if the folder holds non-simulated files")
    a = ap.parse_args()

    t0 = time.time()
    out = Path(a.out)
    if out.exists() and any(out.iterdir()) and not (out / MARKER).exists() and not a.force:
        sys.exit(f"{out} is not empty and has no {MARKER} marker - refusing to overwrite possibly real data. Use another --out or --force.")
    cfg = load_config(Path(a.config), a.size)
    seed = a.seed
    do_bank, do_corp = a.entity in ("bank", "both"), a.entity in ("corporate", "both")
    cal = make_calendar(cfg)
    rc = reporting_currency(cfg)
    H = len(cal.proj_days)
    rng_fx, rng_bank, rng_corp = (np.random.default_rng([seed, i]) for i in (1, 2, 3))
    log = lambda msg: print(f"[{time.time() - t0:6.1f}s] {msg}", flush=True)  # noqa: E731

    if out.exists():
        for f in out.glob("*.csv"):
            f.unlink()
    w = Writer(out)
    (out / MARKER).write_text("generated by liquidity-simulation/scripts/generate.py\n", encoding="utf-8")

    fx = fx_history(cfg, cal, rng_fx)
    drivers = scenarios.resolve_drivers(cfg)
    notes: list[str] = []

    # ---------------- bank
    bank = stress = None
    if do_bank:
        log("bank: contracts, schedules, positions")
        bank = bank_mod.simulate_bank(cfg, cal, fx, rng_bank)
        stress = scenarios.BankStress(bank, cfg, cal)

    # ---------------- corporate history
    corp = None
    if do_corp:
        log("corporate: invoices, actuals, revolver balancing")
        corp = corp_mod.simulate_corporate_history(cfg, cal, fx, rng_corp)

    # ---------------- reverse stress calibration
    def corp_group_survival(d):
        _, bal = corp_mod.forecast_corporate(corp, cfg, cal, d, "REVERSE")
        s = corp_mod.corp_survival(bal, H)["__GROUP__"]
        return s if s is not None else H + 1

    log("reverse stress: calibrating shock multiplier")
    rev, lam, note = scenarios.calibrate_reverse(stress, corp_group_survival if corp else None, cfg, drivers)
    drivers["REVERSE"] = rev
    notes.append(f"Reverse stress multiplier on (COMBINED - BASE) shocks: x{lam:.3f}.")
    if note:
        notes.append(note)

    # ---------------- projections
    stressed, surv = [], {}
    corp_fc, corp_bal, corp_surv = [], {}, {}
    for s in projection_scenarios(cfg):
        d = drivers[s]
        if do_bank:
            f = stress.flows(d, s)
            stressed.append(f)
            surv[s] = stress.survival(f, d)
        if do_corp:
            fc, bal = corp_mod.forecast_corporate(corp, cfg, cal, d, s)
            corp_fc.append(fc)
            corp_bal[s] = bal
            corp_surv[s] = corp_mod.corp_survival(bal, H)
    log("projections done")

    # ---------------- dimensions
    max_date = cal.proj_days[-1]
    if do_bank:
        max_date = max(max_date, bank.flows_contractual["date"].max().to_datetime64().astype("datetime64[D]"))
    days = np.arange(cal.hist_start, max_date + DAY, dtype="datetime64[D]")
    dd = pd.DatetimeIndex(days)
    rel = (days - cal.as_of).astype("int64")
    w.write("dim_date", pd.DataFrame({
        "date": days, "year": dd.year, "quarter": "Q" + dd.quarter.astype(str), "month_number": dd.month,
        "month_name": dd.strftime("%b"), "year_month": dd.strftime("%Y-%m"), "year_month_key": dd.year * 100 + dd.month,
        "day_of_week": dd.strftime("%a"), "is_business_day": np.is_busday(days).astype(int),
        "is_month_end": dd.is_month_end.astype(int), "days_from_asof": rel,
        "period_type": np.select([rel < 0, rel == 0, rel <= H], ["History", "As-of", "Projection"], "Contractual tail"),
    }))
    w.write("dim_currency", pd.DataFrame([{"currency_code": k, "currency_name": v["name"], "rate_to_rc_asof": v["rate_to_rc"],
                                           "is_reporting_currency": int(k == rc)} for k, v in cfg["currencies"].items()]))
    w.write("fact_fx_rate", fx)
    ent = []
    if do_bank:
        ent.append({"entity_code": cfg["bank"]["code"], "entity_name": cfg["bank"]["name"], "entity_type": "Bank",
                    "currency_code": rc, "parent_entity_code": ""})
    if do_corp:
        g = cfg["corporate"]
        ent.append({"entity_code": g["group_code"], "entity_name": g["group_name"], "entity_type": "Corporate",
                    "currency_code": rc, "parent_entity_code": ""})
        for k, v in g["entities"].items():
            ent.append({"entity_code": k, "entity_name": v["name"], "entity_type": "Corporate",
                        "currency_code": v["currency"], "parent_entity_code": g["group_code"]})
    w.write("dim_entity", pd.DataFrame(ent))
    w.write("dim_scenario", pd.DataFrame([{"scenario_key": k, "scenario_name": v["name"], "scenario_type": v["type"],
                                           "sort_order": v["order"], "description": v["description"]}
                                          for k, v in cfg["scenarios"].items()]))
    drv_tbl = scenarios.scenario_parameter_table(cfg, drivers, lam)
    w.write("scenario_parameter", drv_tbl)
    bks = buckets()
    w.write("dim_time_bucket", pd.DataFrame(
        [{"bucket_key": k, "bucket_label": lbl, "from_day": a_, "to_day": b_, "sort_order": i + 1,
          "in_lcr_30d": int(b_ <= 30), "in_6m": int(b_ <= 183), "in_1y": int(b_ <= 365)} for i, (k, lbl, a_, b_) in enumerate(bks)]
        + [{"bucket_key": nm_bucket_key(), "bucket_label": "Non-maturity", "from_day": None, "to_day": None,
            "sort_order": len(bks) + 1, "in_lcr_30d": 0, "in_6m": 0, "in_1y": 0}]))

    # ---------------- facts
    mets = []
    if do_bank:
        w.write("dim_product", bank.dim_product)
        w.write("dim_counterparty_segment", bank.dim_segment)
        w.write("dim_contract", bank.contracts)
        w.write("fact_bank_position", bank.positions)
        w.write("fact_hqla_holding", bank.hqla)
        w.write("fact_bank_cashflow_history", bank.flows_history)
        w.write("fact_bank_cashflow_contractual", bank.flows_contractual)
        st = pd.concat(stressed, ignore_index=True)
        w.write("fact_bank_cashflow_stressed", st)
        w.write("fact_bank_survival", metrics.bank_survival_curve(surv, cal))
        log("bank metrics")
        mets.append(metrics.bank_metrics(bank, cfg, cal, drivers, surv))
        w.write("fact_liquidity_gap", metrics.gap_table(bank, st, cal))
    if do_corp:
        w.write("dim_cf_category", corp.dim_cf_category)
        w.write("dim_counterparty", corp.dim_counterparty)
        w.write("dim_bank_account", corp.dim_bank_account)
        w.write("dim_facility", corp.dim_facility)
        w.write("fact_corp_invoice", corp.invoices)
        w.write("fact_corp_cashflow_actual", corp.actual)
        w.write("fact_corp_cashflow_forecast", pd.concat(corp_fc, ignore_index=True))
        w.write("fact_corp_cash_balance", pd.concat([corp.balances] + list(corp_bal.values()), ignore_index=True))
        mets.append(metrics.corp_metrics(corp, corp_bal, corp_surv, cfg, cal))
    met = pd.concat(mets, ignore_index=True)
    met["survival_days"] = met["survival_days"].astype("Int64")
    w.write("fact_liquidity_metrics", met)

    used = {k: v for k, v in cfg.items() if not k.startswith("_")}
    used["meta"] = dict(used["meta"], seed=seed, entity=a.entity)
    (out / "config_used.yaml").write_text(yaml.safe_dump(used, sort_keys=False, allow_unicode=True), encoding="utf-8")
    elapsed = time.time() - t0
    docs.write_readme(out / "README.md", cfg, w.counts, drv_tbl, met, notes, seed, elapsed)

    total = sum(w.counts.values())
    log(f"wrote {len(w.counts)} tables, {total:,} rows to {out}")
    for n, c in w.counts.items():
        print(f"  {n:34s} {c:>10,}")


if __name__ == "__main__":
    main()
